apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: mumble
    version: v1
  name: mumble
  namespace: mumble
spec:
  replicas: 1
  selector:
    app: mumble
    version: v1
  template:
    metadata:
      labels:
        app: mumble
        version: v1
    spec:
      containers:
      - image: bborbe/mumble:latest
        name: mumble
        ports:
        - containerPort: 64738
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 25Mi
      nodeSelector:
        role: worker
