apiVersion: v1
kind: Service
metadata:
  labels:
    app: taiga
    role: postgres
  name: taiga-postgres
  namespace: taiga
spec:
  ports:
  - name: postgres
    port: 5432
  selector:
    app: taiga
    role: postgres
