apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: backup
    version: v1
  name: backup
  namespace: backup
spec:
  replicas: 1
  selector:
    app: backup
    version: v1
  template:
    metadata:
      labels:
        app: backup
        version: v1
    spec:
      containers:
      - image: bborbe/backup-rsync:latest
        name: backup
        ports:
        - containerPort: 22
          name: backup
        resources:
          limits:
            cpu: 1000m
            memory: 200Mi
          requests:
            cpu: 250m
            memory: 100Mi
        volumeMounts:
        - mountPath: /data
          name: backup
          readOnly: true
        - mountPath: /etc/ssh
          name: backup-ssh
          readOnly: true
      nodeSelector:
        role: worker
      volumes:
      - name: backup
        nfs:
          path: /data
          server: {{nfs_server}}
      - name: backup-ssh
        nfs:
          path: /data/backup-ssh
          server: {{nfs_server}}
