apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: aptly
    role: cleanup
  name: aptly-cleanup
  namespace: aptly
spec:
  replicas: 1
  selector:
    app: aptly
    role: cleanup
  template:
    metadata:
      labels:
        app: aptly
        role: cleanup
    spec:
      containers:
      - env:
        - name: LOGLEVEL
          value: debug
        - name: DELAY
          value: 4h
        - name: URL
          value: http://aptly-api:3845
        image: bborbe/aptly-dbcleanup-cron:latest
        name: aptly-cleanup
        resources:
          limits:
            cpu: 200m
            memory: 25Mi
          requests:
            cpu: 10m
            memory: 5Mi
      nodeSelector:
        role: worker
