apiVersion: v1
kind: Service
metadata:
  labels:
    app: aptly
    role: api
  name: aptly-api
  namespace: aptly
spec:
  ports:
  - name: api
    port: 3845
  - name: api-auth
    port: 3846
  selector:
    app: aptly
    role: api
