apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: taiga
    role: frontend
    version: v1
  name: taiga-frontend
  namespace: taiga
spec:
  replicas: 1
  selector:
    app: taiga
    role: frontend
    version: v1
  template:
    metadata:
      labels:
        app: taiga
        role: frontend
        version: v1
    spec:
      containers:
      - image: bborbe/taiga-frontend:latest
        env:
        - name: PUBLIC_HOSTNAME
          value: "http://taiga.tools.seibert-media.net/api/v1/"
        - name: PUBLIC_REGISTER_ENABLED
          value: "true"
        name: taiga-frontend
        ports:
        - containerPort: 80
          name: taiga-frontend
        resources:
          limits:
            cpu: 250m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 30Mi
      nodeSelector:
        role: worker
