apiVersion: v1
kind: Service
metadata:
  labels:
    app: taiga
    role: public
    romulus/lb: vulcan
    romulus/route: public
  name: taiga-media
  namespace: taiga
spec:
  ports:
  - name: media
    port: 80
  selector:
    app: taiga
    role: public
