apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: taiga
    role: postgres
    version: v1
  name: taiga-postgres
  namespace: taiga
spec:
  replicas: 1
  selector:
    app: taiga
    role: postgres
    version: v1
  template:
    metadata:
      labels:
        app: taiga
        role: postgres
        version: v1
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: {{taiga_database_password}}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: taiga
        - name: POSTGRES_DB
          value: taiga
        image: postgres
        name: taiga-postgres
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          limits:
            cpu: 1000m
            memory: 100Mi
          requests:
            cpu: 250m
            memory: 50Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: taiga-postgres
      nodeSelector:
        role: worker
      volumes:
      - name: taiga-postgres
        nfs:
          path: /data/taiga-postgres
          server: {{nfs_server}}
