apiVersion: v1
kind: Service
metadata:
  labels:
    app: taiga
    role: backend
    romulus/lb: vulcan
    romulus/route: public
  name: taiga-backend
  namespace: taiga
spec:
  ports:
  - name: backend
    port: 8000
  selector:
    app: taiga
    role: backend
