apiVersion: v1
kind: Service
metadata:
  labels:
    app: taiga
    role: backend
    romulus/lb: vulcan
    romulus/route: public
  name: taiga-static
  namespace: taiga
spec:
  ports:
  - name: static
    port: 80
  selector:
    app: taiga
    role: backend
