apiVersion: v1
kind: Service
metadata:
  labels:
    app: heapster
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Grafana
  name: heapster-grafana
  namespace: kube-system
spec:
  ports:
  - name: web
    nodePort: 30001
    port: 3000
  selector:
    k8s-app: influxGrafana
  type: NodePort
