apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    role: haproxy-exporter
  name: prometheus-haproxy
  namespace: kube-system
spec:
  ports:
  - name: exporter
    port: 9101
  selector:
    app: prometheus
    role: haproxy-exporter
