apiVersion: v1
kind: Secret
metadata:
  labels:
    app: merge-bot
  name: merge-bot
  namespace: merge-bot
type: Opaque
data:
  username: {{github_username_base64}}
  password: {{github_password_base64}}
