apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: merge-bot
    version: v1
  name: merge-bot
  namespace: merge-bot
spec:
  replicas: 1
  selector:
    app: merge-bot
    version: v1
  template:
    metadata:
      labels:
        app: merge-bot
        version: v1
    spec:
      containers:
      - env:
        - name: LOGLEVEL
          value: debug
        - name: PORT
          value: "8080"
        - name: PREFIX
          value: /merge-bot
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: merge-bot
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: merge-bot
        image: bborbe/merge-bot:latest
        name: merge-bot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
      nodeSelector:
        role: worker
