apiVersion: v1
kind: Service
metadata:
  labels:
    app: bot
    role: connector-fb-sm
    romulus/lb: vulcan
    romulus/route: public
  name: bot-connector-fb-sm
  namespace: bot
spec:
  ports:
  - name: web
    port: 8080
  selector:
    app: bot
    role: connector-fb-sm
