apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: bot
    role: connector-fb-hq
    version: v1
  name: bot-connector-fb-hq
  namespace: bot
spec:
  replicas: 1
  selector:
    app: bot
    role: connector-fb-hq
    version: v1
  template:
    metadata:
      labels:
        app: bot
        role: connector-fb-hq
        version: v1
    spec:
      containers:
      - env:
        - name: LOGLEVEL
          value: debug
        - name: PORT
          value: "8080"
        - name: DEBUG
          value: "true"
        - name: PREFIX
          value: "/bot/facebook/highrise"
        - name: MASTER
          value: bot-master:8080
        - name: BOT_NAME
          value: SeibertMediaBot
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: facebook-secret-hq
              name: bot
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: facebook-token-hq
              name: bot
        image: bborbe/bot-connector-facebook:latest
        name: connector-fb-hq
        ports:
        - containerPort: 8080
          name: bot
        resources:
          limits:
            cpu: 500m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
      nodeSelector:
        role: worker
