apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: maven
    role: api
    version: v1
  name: maven-api
  namespace: maven
spec:
  replicas: 1
  selector:
    app: maven
    role: api
    version: v1
  template:
    metadata:
      labels:
        app: maven
        role: api
        version: v1
    spec:
      containers:
      - image: bborbe/maven-repo:latest
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: api
        ports:
        - containerPort: 8080
          name: api
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - mountPath: /data
          name: maven
      nodeSelector:
        role: worker
      volumes:
      - name: maven
        nfs:
          path: /data/maven
          server: {{nfs_server}}
