apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: hello-world
    version: v1
  name: hello-world
  namespace: hello-world
spec:
  replicas: 1
  selector:
    app: hello-world
    version: v1
  template:
    metadata:
      labels:
        app: hello-world
        version: v1
    spec:
      containers:
      - image: bborbe/hello-world:latest
        name: hello-world
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
      nodeSelector:
        role: worker
