apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: bot
    role: connector-telegram-hq
    version: v1
  name: bot-connector-telegram-hq
  namespace: bot
spec:
  replicas: 1
  selector:
    app: bot
    role: connector-telegram-hq
    version: v1
  template:
    metadata:
      labels:
        app: bot
        role: connector-telegram-hq
        version: v1
    spec:
      containers:
      - env:
        - name: LOGLEVEL
          value: debug
        - name: PORT
          value: "8080"
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: telegram-token-hq
              name: bot
        - name: DEBUG
          value: "true"
        - name: ONE_TIME
          value: "false"
        - name: MASTER
          value: bot-master:8080
        image: bborbe/bot-connector-telegram:latest
        name: connector-telegram-hq
        ports:
        - containerPort: 8080
          name: bot
        resources:
          limits:
            cpu: 500m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
      nodeSelector:
        role: worker
