apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: storage
    version: v1
  name: storage-api
  namespace: storage
spec:
  replicas: 1
  selector:
    app: storage
    role: api
    version: v1
  template:
    metadata:
      labels:
        app: storage
        role: api
        version: v1
    spec:
      containers:
      - image: bborbe/storage:latest
        env:
        - name: LOGLEVEL
          value: debug
        - name: PORT
          value: "8080"
        - name: ROOT
          value: "/data"
        - name: AUTH_ADDRESS
          value: "auth-api.auth.svc.cluster.local:8080"
        - name: AUTH_APPLICATION_NAME
          value: "storage"
        - name: AUTH_APPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: storage
              key: auth-application-password
        name: storage
        volumeMounts:
        - mountPath: /data
          name: data
        ports:
        - containerPort: 8080
          name: storage
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
      nodeSelector:
        role: worker
      volumes:
      - name: data
        nfs:
          path: /data
          server: {{nfs_server}}
