apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: auth
    version: v1
  name: auth-api
  namespace: auth
spec:
  replicas: 1
  selector:
    app: auth
    role: api
    version: v1
  template:
    metadata:
      labels:
        app: auth
        role: api
        version: v1
    spec:
      containers:
      - env:
        - name: LOGLEVEL
          value: debug
        - name: PORT
          value: "8080"
        - name: LEDISDB_ADDRESS
          value: auth-ledisdb:6380
        - name: AUTH_APPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              key: auth-application-password
              name: auth
        image: bborbe/auth:latest
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: auth
        ports:
        - containerPort: 8080
          name: auth
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
      nodeSelector:
        role: worker
