apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: ip
    version: v1
  name: ip
  namespace: ip
spec:
  replicas: 1
  selector:
    app: ip
    version: v1
  template:
    metadata:
      labels:
        app: ip
        version: v1
    spec:
      containers:
      - env:
        - name: LOGLEVEL
          value: debug
        - name: PORT
          value: "8080"
        image: bborbe/ip:latest
        name: ip
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
      nodeSelector:
        role: worker
