apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nsq
    role: nsqd
    version: v1
  name: nsqd
  namespace: nsq
spec:
  replicas: 1
  selector:
    app: nsq
    role: nsqd
    version: v1
  template:
    metadata:
      labels:
        app: nsq
        role: nsqd
        version: v1
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - /nsqd --broadcast-address=$$(hostname -i) --lookupd-tcp-address=nsqlookupd:4160
        image: nsqio/nsq:latest
        name: nsqd
        ports:
        - containerPort: 4150
          name: tcp
        - containerPort: 4151
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
      nodeSelector:
        role: worker
