apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nsq
    role: nsqlookupd
    version: v1
  name: nsqlookupd
  namespace: nsq
spec:
  replicas: 1
  selector:
    app: nsq
    role: nsqlookupd
    version: v1
  template:
    metadata:
      labels:
        app: nsq
        role: nsqlookupd
        version: v1
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - /nsqlookupd --broadcast-address=$$(hostname -i)
        image: nsqio/nsq:latest
        name: nsqlookupd
        ports:
        - containerPort: 4160
          name: tcp
        - containerPort: 4161
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
      nodeSelector:
        role: worker
