apiVersion: v1
kind: Service
metadata:
  labels:
    app: nsq
    role: nsqadmin
  name: nsqadmin
  namespace: nsq
spec:
  ports:
  - nodePort: 30029
    port: 4171
  selector:
    app: nsq
    role: nsqadmin
  type: NodePort
