apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: aptly
    role: public
    version: v1
  name: aptly-public
  namespace: aptly
spec:
  replicas: 1
  selector:
    app: aptly
    role: public
    version: v1
  template:
    metadata:
      labels:
        app: aptly
        role: public
        version: v1
    spec:
      containers:
      - image: jrelva/nginx-autoindex
        name: aptly-public
        ports:
        - containerPort: 80
          name: web
        resources:
          limits:
            cpu: 250m
            memory: 25Mi
          requests:
            cpu: 10m
            memory: 5Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: aptly-public
          readOnly: true
      nodeSelector:
        role: worker
      volumes:
      - name: aptly-public
        nfs:
          path: /data/aptly/public
          server: {{nfs_server}}
