apiVersion: v1
kind: Service
metadata:
  labels:
    app: aptly
    role: api
    romulus/lb: vulcan
    romulus/route: public
  name: aptly-auth-api
  namespace: aptly
spec:
  ports:
  - name: web
    port: 3846
  selector:
    app: aptly
    role: api
