apiVersion: v1
kind: Service
metadata:
  labels:
    app: heapster
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: InfluxDB
  name: heapster-influxdb
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  - name: api
    port: 8086
    targetPort: 8086
  selector:
    k8s-app: influxGrafana
