apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: jenkins
    role: slave-java
    version: v1
  name: jenkins-slave-java
  namespace: jenkins
spec:
  replicas: 1
  selector:
    app: jenkins
    role: slave-java
    version: v1
  template:
    metadata:
      labels:
        app: jenkins
        role: slave-java
        version: v1
    spec:
      containers:
      - env:
        - name: JENKINS_URL
          value: http://$(JENKINS_MASTER_SERVICE_HOST):$(JENKINS_MASTER_SERVICE_PORT_WEB)
        - name: JENKINS_TUNNEL
          value: $(JENKINS_MASTER_SERVICE_HOST):$(JENKINS_MASTER_SERVICE_PORT_LEADER)
        - name: JENKINS_SECRET
          value: 68fb899217e49533750bd9adbe2999a4974ea098e9ce2834f573f94374e161a1
        - name: JENKINS_NODE
          value: slave-java
        - name: JENKINS_OPTS
          value: -noreconnect
        - name: JAVA_OPTS
          value: -Xmx100m -Dcom.sun.management.jmxremote= -Dcom.sun.management.jmxremote.port=1099
            -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
        image: bborbe/jenkins-jnlp-slave-java:latest
        name: jenkins-slave-java
        resources:
          limits:
            cpu: 2000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
        volumeMounts:
        - mountPath: /home/jenkins
          name: jenkins-slave-java
      nodeSelector:
        role: worker
      volumes:
      - name: jenkins-slave-java
        nfs:
          path: /data/jenkins-slave-java
          server: {{nfs_server}}
