apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    role: backend
  name: prometheus
  namespace: kube-system
spec:
  ports:
  - nodePort: 30002
    port: 9090
  selector:
    app: prometheus
    role: backend
  type: NodePort
