apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: minecraft
    version: v1
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  selector:
    app: minecraft
    version: v1
  template:
    metadata:
      labels:
        app: minecraft
        version: v1
    spec:
      containers:
      - image: bborbe/minecraft:latest
        name: minecraft
        ports:
        - containerPort: 20000
          name: minecraft
        resources:
          limits:
            cpu: 1000m
            memory: 700Mi
          requests:
            cpu: 250m
            memory: 650Mi
        volumeMounts:
        - mountPath: /opt/msm
          name: minecraft
      nodeSelector:
        role: worker
      volumes:
      - name: minecraft
        nfs:
          path: /data/minecraft
          server: {{nfs_server}}
